SELECT WAREHOUSE_ID, 
    WAREHOUSE_NAME, 
    ADDRESS, 
    CASE WHEN FREEZER_YN is NULL THEN 'N'
    WHEN FREEZER_YN is not null then FREEZER_YN
    END AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE('%경기도%')
ORDER BY 1 ASC