SELECT BOOK.CATEGORY, SUM(BOOK_SALES.SALES) TOTAL_SALES
FROM BOOK INNER JOIN BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE DATE_FORMAT(BOOK_SALES.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY BOOK.CATEGORY
ORDER BY 1 ASC